### ISSUE TITLE
Problems in Black box interconnection

### ISSUE THREAD

**Issue by maths644311798** [secretflow/yacl#102]
(1)	Are there any more explanations about “Black box interconnection transport layer protocol” than blackbox_service.proto?
	
(2)	It seems that the difference between ChannelBrpcBlackBox and ChannelBrpc is: the former builds a channel via environment variables while the latter inputs information explicitly. What’s the main reason to write these two classes of channels instead of one?

(3)	Many error codes are defined in blackbox_service_errorcode.h. But where are they set? For example, where is the code that sets “QueueFull”?

**Comment by huocun-ant** [comment]
1. The `blackbox_service.proto` is for `UnionPay  Privacy Computing Interconnection Agreement`. You can search related reports，like [this report](https://www.sohu.com/a/676133615_121049112). 
2. `ChannelBrpc` is for is for direct connection communication between two engines, while `ChannelBrpcBlackBox` is intended for use on interconnected platforms, the channel will communicate with a `transport service` which is is managed and scheduled by a framework, like [KUSIA](https://github.com/secretflow/kuscia).
3. These `errorcode` is defined by the agreement, add would be set by the `transport service`. Like this:
![image](https://github.com/secretflow/yacl/assets/131865681/3cdfb10a-789d-41b4-acab-e8a979925d31)

It does take a lot of background information to understand `ChannelBrpcBlackBox`, but maybe you can ignore it because basically it's just a way of sending and receiving messages.

**Comment by Eiji911** [comment]
error code is defined in https://github.com/be-io/interconnection-bfia/blob/main/bfia/mesh/api/Specifications_CN.md，and we add three  error  code which will be append to the Specifications_CN.md lately。

**Comment by maths644311798** [comment]
@huocun-ant 

>    ![image](https://user-images.githubusercontent.com/131865681/256227609-3cdfb10a-789d-41b4-acab-e8a979925d31.png)

In the picture,  should the text below "pop_request" be "response(pop)"?

**Comment by huocun-ant** [comment]
> @huocun-ant
> 
> > ![image](https://user-images.githubusercontent.com/131865681/256227609-3cdfb10a-789d-41b4-acab-e8a979925d31.png)
> 
> In the picture, should the text below "pop_request" be "response(pop)"?

It's the same. 
What I want to express is that if B wants to receive the message (headshake_request) sent to it by A, it needs to call the pop operation of the transport service B, transport service B will put the previously cached message "headshake_request" into "response(pop)"，and B will be considered to have received the message.

**Comment by huocun-ant** [comment]
@maths644311798 
To be precise, all responses from the transport service to comp are `TransportOutbound`.
https://github.com/secretflow/yacl/blob/main/yacl/link/transport/blackbox_interconnect/blackbox_service.proto#L25C1-L25C1
And `payload` may be empty.
