### ISSUE TITLE
yacl/crypto/tpre/kdf的问题

### ISSUE THREAD

**Issue by maths644311798** [secretflow/yacl#303]
在yacl/crypto/tpre/kdf.cc中，kdf的实现和SM2的文档(就是kdf.h给的[文档](http://www.sca.gov.cn/sca/xwdt/2010-12/17/1002386/files/b791a9f908bb4803875ab6aeeb7b4e03.pdf) )不一致。这段代码
```
    if (i == index - 1) {
      if (key_len % 32 != 0) {
        dgst_len = (key_len) % 32;
      } else {
        dgst_len = 0;
      }
    }
```
中key_len被32整除时，按照文档的做法，应该是设置dgst_len = 32. 下面抄录文档这一句

若klen/v是整数，令Ha!<sub>klen/v</sub> = Ha<sub>klen/v</sub>

**Comment by Jamie-Cui** [comment]
This code was contributed by external developers, it will take some time for us to verify. @xfap Would you like to take a look?

**Comment by xfap** [comment]
@maths644311798 Hi, the kdf function here is not a wrong implementation but a different impl. way. The reason for setting to 0 instead of 32, is bacause the index is setted as `int index = (key_len + 32) / 32;`. When `key_len%32==0`, there will be a redundant hash round, so the last dgst_len should set to 0.
