### ISSUE TITLE
Do not need to reset in the constructor of Hmac

### ISSUE THREAD

**Issue by maths644311798** [secretflow/yacl#75]
In yacl/crypto/base/hmac.cc, the constructor is

Hmac::Hmac(HashAlgorithm hash_algo, ByteContainerView key)
    : hash_algo_(hash_algo),
      key_(key.begin(), key.end()),
      context_(CheckNotNull(HMAC_CTX_new())) {
  Reset();
}

where Reset() is 

Hmac& Hmac::Reset() {
  YACL_ENFORCE_EQ(HMAC_CTX_reset(context_), 1);
  Init_HMAC(hash_algo_, key_, context_);
  return *this;
}

I don't think that we need to invoke Reset() in the constructor. My suggestion is that the following code is better:

Hmac::Hmac(HashAlgorithm hash_algo, ByteContainerView key)
    : hash_algo_(hash_algo),
      key_(key.begin(), key.end()),
      context_(CheckNotNull(HMAC_CTX_new())) {
  Init_HMAC(hash_algo_, key_, context_);
}

The reason is that HMAC_CTX_new() already invokes HMAC_CTX_reset().

**Comment by Jamie-Cui** [comment]
Hi, thanks for the suggestion, the openssl official doc ([here](https://www.openssl.org/docs/man3.1/man3/HMAC_CTX_reset.html)) says that:
> HMAC_CTX_reset() clears an existing HMAC_CTX and associated resources, making it suitable for new computations as if it was newly created with HMAC_CTX_new().

I suppose that is exactly what we need in `Hmac::Reset()`. Also your suggested code would additionally calls the copy construction or `HMAC_CTX`, which may or may not have an impact on efficiency (since I haven't checkout openssl's implementation details :p).
